### ISSUE TITLE
Shouldn't the ion_schema::violation be `pub`?

### ISSUE THREAD

**Issue by dlurton** [amazon-ion/ion-schema-rust#135]
It's currently [not `pub`](https://github.com/amazon-ion/ion-schema-rust/blob/dc56c9cd08627784410804bc556395f111b6ada9/ion-schema/src/lib.rs#L32).  This prevents `ion_schema::violation::Violation` from being referenced explicitly in customer code.

The impact is that the customer code cannot reference the type explicitly.  For instance this code works fine:

```
let type_ref: TypeRef = ...;
let r = type_ref.validate(some_element);
let e = r.unwrap_err();
// e can be used normally
```

But try to declare an explicit type for `e`:

```
let e: ion_schema::violation::Violation = r.unwrap_err();
//                 ^ error, mod is private
```

`use ion_schema::violation::Violation` doesn't work either.

TBH, it's a bit surprising to me that Rust allows you to return a type from `Type_Ref::validate()` that isn't in a public module.

**Comment by desaikd** [comment]
Fixed with #139
