### ISSUE TITLE
Please fix Ion rust issue & release.

### ISSUE THREAD

**Issue by dlurton** [amazon-ion/ion-schema-rust#146]
Please fix https://github.com/amazon-ion/ion-rust/issues/425, release `ion_rs`, change `ion-schema-rust` to re-export the newly released version of `ion-rs` (or alternatively complete #137) and then release `ion_schema_rust`.

**Comment by desaikd** [comment]
The ion-rs issue has been fixed with `v0.16.0` release. Closing this as it has been included in the latest release of `ion-schema-rust` `v0.7.0`.
