### ISSUE TITLE
Make `SchemaSystem` thread-safe

### ISSUE THREAD

**Issue by sadderchris** [amazon-ion/ion-schema-rust#151]
Right now, since `SchemaSystem` is `!Send` and `!Sync`, it can't be used from multiple threads concurrently or even passed between multiple threads.  If we want to validate an Ion document in a multithreaded environment, we need to instantiate a new `SchemaSystem` for each thread, which isn't great for performance.

Ideally, we should be able to load an ISL schema once and re-use it from multiple threads without having to (re)parse it every time.

**Comment by popematt** [comment]
I think there is some overlap between this issue and #150.

This is pretty off-the-cuff, but I wonder if we can solve them both by decoupling the loading of a schema from the management/caching of the schemas.

Suppose we define two traits:
```rust
// The point is that this trait should be some sort of unification across things like Arc<Schema>,
// Box<Schema>, Rc<Schema>, etc. so that regardless of how the user chooses to handle the 
// memory management of the cached schemas, the other parts of the ISL implementation will still work.
trait SchemaRef: Clone {
    fn new(schema: Schema) -> Self;
    fn as_schema(self) -> &Schema
}

trait SchemaCache {
    type SchemaType: SchemaRef;

    fn get_or_put(&mut self, id: String, schema: fn() -> Schema) -> Self::SchemaType;
    fn get(&self, id: String) -> Option<Self::SchemaType>;
    fn invalidate(&mut self, id: String) -> IonSchemaResult<()>;
}
```

And we define a separate loader (function), such as this:
```rust
/// Loads the requested schema, along with any direct and transient imports
fn load_schema(id: String, authorities: &Vec<Authority>) -> IonSchemaResult<(Schema, Vec<Schema>)>;
```

Then with a bit of glue code, we can put together a `SchemaSystem` that wraps this loader function and a `SchemaCache`. Depending on the `SchemaCache` being used, the `SchemaSystem` could be `Send`/`Sync`, I think.

Obviously this idea needs some refinement if it's going to work, but it _might_ be a decent place to start.
