### ISSUE TITLE
Implementation of a `StateMachine` for validation

### ISSUE THREAD

**Issue by desaikd** [amazon-ion/ion-schema-rust#56]
As part of the validation of `ordered_elements` constraint, it would require to implement a State Machine which can keep track of `occurs` constraint and move to another state as per events(e.g. `type:int`) .  

**Example:**
For a constraint `ordered_elements: [int, decimal]`, State Machine constructs an NFA like below:
```
 InitialState --event1--> IntermediateState --event2--> FinalState
 S1:required --type:int--> S2:required --type:decimal--> S3:optional
```
*Note::By default the `occurs` constraint would be `required` meaning `range::[1,1]`*

Given below is a summary tale representing the states and events for a value to be validated:

 value: [1, 2.0]
 
| Event            | State set (each state represented by state:visitCount)|
| -------------|------------------------------------------------------|
|                      | (initial state) |
| type:int         | S1:1 |
| type:decimal     | S2:1 --> matches! |

value: [2.0, 1]

 | Event             | State set (each state represented by state:visitCount)|
 |--------------|-----------------------------------------------------|
 |                       | (initial state)                                     |
 | type:int          | S1:0 --> no matches! expected int found decimal value

Prerequisite PR: #55 (`contains` implementation is required to be used within `occurs` constraint while `ordered_elements` constraint validation)

**Comment by desaikd** [comment]
This is fixed because `ordered_elements` has been implemented  in a simpler way by using a peekable iterator instead with #62.

**Comment by popematt** [comment]
Reopening because according to https://github.com/amzn/ion-schema/issues/62, `ordered_elements` should be treated more like a regular expression/language. We will need something other than the peekable iterator to evaluate it. It will probably need a state machine, but it is possible that there is some other solution.

**Comment by popematt** [comment]
[Here](https://amzn.github.io/ion-schema/sandbox?schema=type%3A%3A%7B%0A%20%20name%3A%20my_sexp%2C%0A%20%20type%3A%20sexp%2C%0A%20%20ordered_elements%3A%20%5B%0A%20%20%20%20%7B%20occurs%3A%20optional%2C%20type%3A%20any%20%7D%2C%0A%20%20%20%20%7B%20occurs%3A%20optional%2C%20type%3A%20number%20%7D%2C%0A%20%20%20%20%7B%20occurs%3A%20required%2C%20type%3A%20int%20%7D%2C%0A%20%20%5D%2C%0A%7D&value=(1)&type=my_sexp) is an example of something that should be valid, but is not recognized as valid.
